/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kisisewamobil;

import static java.awt.Component.CENTER_ALIGNMENT;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author N Aditiya
 */
public class Halaman_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Halaman_Utama
     */
    public Halaman_Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnkeluar = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmdsimpan = new javax.swing.JButton();
        txkmb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txjdl = new javax.swing.JTextField();
        txharga = new javax.swing.JTextField();
        txno = new javax.swing.JTextField();
        txkode = new javax.swing.JTextField();
        txpnj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        optedit = new javax.swing.JRadioButton();
        optbaru = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grd_sewa = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sewa Mobil 99");

        btnkeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnkeluar.setForeground(new java.awt.Color(0, 0, 0));
        btnkeluar.setText("Keluar");
        btnkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkeluarMouseClicked(evt);
            }
        });

        cmdhapus.setBackground(new java.awt.Color(255, 255, 255));
        cmdhapus.setForeground(new java.awt.Color(0, 0, 0));
        cmdhapus.setText("Hapus");
        cmdhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdhapusMouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Judul Mobil");

        cmdsimpan.setBackground(new java.awt.Color(255, 255, 255));
        cmdsimpan.setForeground(new java.awt.Color(0, 0, 0));
        cmdsimpan.setText("Simpan");
        cmdsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdsimpanMouseClicked(evt);
            }
        });

        txkmb.setBackground(new java.awt.Color(51, 51, 51));
        txkmb.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No Plat Mobil");

        txjdl.setBackground(new java.awt.Color(51, 51, 51));
        txjdl.setForeground(new java.awt.Color(255, 255, 255));

        txharga.setBackground(new java.awt.Color(51, 51, 51));
        txharga.setForeground(new java.awt.Color(255, 255, 255));

        txno.setBackground(new java.awt.Color(51, 51, 51));
        txno.setForeground(new java.awt.Color(255, 255, 255));

        txkode.setBackground(new java.awt.Color(51, 51, 51));
        txkode.setForeground(new java.awt.Color(0, 0, 0));
        txkode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txkodeFocusLost(evt);
            }
        });
        txkode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txkodeKeyReleased(evt);
            }
        });

        txpnj.setBackground(new java.awt.Color(51, 51, 51));
        txpnj.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Peminjaman");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(optedit);
        optedit.setForeground(new java.awt.Color(255, 255, 255));
        optedit.setText("Edit");
        optedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opteditMouseClicked(evt);
            }
        });

        buttonGroup1.add(optbaru);
        optbaru.setForeground(new java.awt.Color(255, 255, 255));
        optbaru.setText("Baru");
        optbaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optbaruMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(optedit)
                .addGap(28, 28, 28)
                .addComponent(optbaru)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optedit)
                    .addComponent(optbaru))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Sewa");

        grd_sewa.setBackground(new java.awt.Color(51, 51, 51));
        grd_sewa.setForeground(new java.awt.Color(255, 255, 255));
        grd_sewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pinjam", "NoPol", "Judul Mobil", "Harga", "Tgl_Pinjam", "Tgl_Kembali"
            }
        ));
        grd_sewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grd_sewaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grd_sewa);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Kembali");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Peminjaman");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnkeluar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmdhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdsimpan))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(135, 135, 135))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(159, 159, 159)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txno)
                                    .addComponent(txkode)
                                    .addComponent(txharga)
                                    .addComponent(txpnj)
                                    .addComponent(txkmb)
                                    .addComponent(txjdl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txjdl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txpnj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txkmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    String koneksi="jdbc:mysql://localhost:3306/dbkisikisi";
    String user = "root";
    String pass = "";
    Connection connection;
    Statement statement;
    
        private void bersih(){
        txkode.setText("");
        txno.setText("");
        txharga.setText("");
        txpnj.setText("");
        txkode.requestFocus();
        txkode.setEnabled(true);
        optbaru.setSelected(true);
        optedit.setSelected(false);
        cmdhapus.setEnabled(false);
        cmdsimpan.setEnabled(false);
        
        try{
            String sql="select * from tb_sewa";
            ResultSet rs=statement.executeQuery(sql);
            final String[] headers={"Kode","No","Judul","Harga","Tglsewa","Tglkmb"};
            rs.last();
            int n=rs.getRow();
            Object[][] data=new Object[n][6];
            int p=0;
            rs.beforeFirst();
            while (rs.next()){
                data[p][0]=rs.getString(1);
                data[p][1]=rs.getString(2);
                data[p][2]=rs.getString(3);
                data[p][3]=rs.getString(4);
                data[p][4]=rs.getString(5);
                data[p][5]=rs.getString(6);
                p++;
            }
            grd_sewa.setModel(new javax.swing.table.DefaultTableModel(data,headers));
            grd_sewa.setAlignmentX(CENTER_ALIGNMENT);
        }
        catch(Exception DBException){
            System.err.println("Error : " + DBException);
        }
        
    }
        
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String koneksi="jdbc:mysql://localhost:3306/dbkisikisi";
            Connection connection=DriverManager.getConnection(koneksi, user, pass);
            statement = connection.createStatement();
        }
        catch(Exception DBException){
            JOptionPane.showMessageDialog(this,"Koneksi Gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error : "+ DBException);
        }
        bersih();
    }                                 

    private void btnkeluarMouseClicked(java.awt.event.MouseEvent evt) {                                       
       System.exit(0);
    }                                      

    private void optbaruMouseClicked(java.awt.event.MouseEvent evt) {                                     
        bersih();
    }                                    

    private void grd_sewaMouseClicked(java.awt.event.MouseEvent evt) {                                      
        if(optedit.isSelected()){
        txkode.setText(grd_sewa.getValueAt(grd_sewa.getSelectedRow(), 0).toString());
        txno.setText(grd_sewa.getValueAt(grd_sewa.getSelectedRow(), 1).toString());
        txjdl.setText(grd_sewa.getValueAt(grd_sewa.getSelectedRow(), 2).toString());
        txharga.setText(grd_sewa.getValueAt(grd_sewa.getSelectedRow(), 3).toString());
        txpnj.setText(grd_sewa.getValueAt(grd_sewa.getSelectedRow(), 4).toString());
        txkmb.setText(grd_sewa.getValueAt(grd_sewa.getSelectedRow(), 5).toString());
        }
        //txkode.setEnabled(false);
        cmdhapus.setEnabled(true);
        cmdsimpan.setEnabled(true);
    }                                     

    private void cmdsimpanMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if(cmdsimpan.isEnabled()==false){
            return;
        }
        
        try{
            String sql;
            if(optbaru.isSelected()){
                sql="insert into tb_sewa values('";
                sql+=txkode.getText()+"','";
                sql+=txno.getText()+"','";
                sql+=txjdl.getText()+"','";
                sql+=txharga.getText()+"','";
                sql+=txpnj.getText()+"','";
                sql+=txkmb.getText()+"')";
            }
            else{
                sql="update tb_sewa set kode_pinjam='";
                sql+=txkode.getText()+"',no_plat='";
                sql+=txno.getText()+"',judul_mobil='";
                sql+=txjdl.getText()+"',harga='";
                sql+=txharga.getText()+"',tgl_pinjam='";
                sql+=txpnj.getText()+"',tgl_kembali='";
                sql+=txkmb.getText()+"' ";
                sql+="where kode_pinjam='"+txkode.getText()+"'";
            }
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Simpan / Update Data Berhasil",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception DBException){
            JOptionPane.showMessageDialog(this, "Simpan / Update Data Gagal",
                   "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error : " + DBException);
        }
        bersih();
    }                                      

    private void txkodeKeyReleased(java.awt.event.KeyEvent evt) {                                   
        if (txkode.getText().equals("")){
            cmdsimpan.setEnabled(false);
        }else{
            cmdsimpan.setEnabled(true);
        }
    }                                  

    private void txkodeFocusLost(java.awt.event.FocusEvent evt) {                                 
                try{
            String sql="select * from tb_sewa where kode_pinjam= '" + txkode.getText() + "'";
            ResultSet rs=statement.executeQuery(sql);
            rs.last();
            int n= rs.getRow();
            if (n>0){
                JOptionPane.showMessageDialog(this, "Kode ('" +txkode.getText()+"')"+ " sudah ada, silahkan ganti !", "Peringatan", JOptionPane.WARNING_MESSAGE);
                bersih();
            }
        }
        catch(Exception DBException){
            JOptionPane.showMessageDialog(this,"Koneksi Gagal", "Error",JOptionPane.ERROR_MESSAGE);
        bersih();
        }
    }                                

    private void cmdhapusMouseClicked(java.awt.event.MouseEvent evt) {                                      
        if (cmdhapus.isEnabled()==false){
            return;
        }
        try{
            String sql="delete from tb_sewa where kode_pinjam='" + txkode.getText() + "'";
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Hapus data berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception DBException){
           JOptionPane.showMessageDialog(this, "Hapus data gagal", "Error", JOptionPane.ERROR_MESSAGE);
           System.err.println("Error : " + DBException);
        }
        bersih();
    }                                     

    private void opteditMouseClicked(java.awt.event.MouseEvent evt) {                                     
        if(grd_sewa.getRowCount()<1){
            JOptionPane.showMessageDialog(this, "Tidak ada data untuk diedit !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        bersih();
        }
    }                                    

    /**
     * @param args the command line argumentss
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnkeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JButton cmdsimpan;
    private javax.swing.JTable grd_sewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton optbaru;
    private javax.swing.JRadioButton optedit;
    private javax.swing.JTextField txharga;
    private javax.swing.JTextField txjdl;
    private javax.swing.JTextField txkmb;
    private javax.swing.JTextField txkode;
    private javax.swing.JTextField txno;
    private javax.swing.JTextField txpnj;
    // End of variables declaration                   
}
